name: Test publish package to TestPyPI

on:
  # Allows manually running this workflow from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Update package version from tag
      run: scripts/update-version.sh src/ocsf_schema_compiler/__init__.py "${{ github.ref_name }}"

    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"

    - name: Build test release distributions
      run: |
        python -m pip install -U flit
        flit build

    - name: Check package version update
      run: |
        flit install
        # If this fails, something went wrong updating the version
        ocsf-schema-compiler -v

    - name: Upload test distributions
      uses: actions/upload-artifact@v7
      with:
        name: test-release-dists
        path: dist/

  publish-to-testpypi:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see:
    #   https://docs.pypi.org/trusted-publishers/adding-a-publisher/
    #   https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    # This is also relevant, though the "on" condition is different:
    #   https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ocsf-schema-compiler

    steps:
      - name: Retrieve test release distributions
        uses: actions/download-artifact@v8
        with:
          name: test-release-dists
          path: dist/

      - name: Publish test release distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
